### PR TITLE
Added a simple abstract for modelling parent/child relationships

### PR DESCRIPTION
**Pull request by gileadslostson**
Abstract model for creating basic hierarchical relationships.

### CODE REVIEW

**Comment by Marwan2001** [comment]
Please comment your code a bit more.

**Comment by gileadslostson** [comment]
@Marwan2001 done. Please let me know if I can improve on them. And thanks for the repo!

**Comment by Marwan2001** [comment]
@gileadslostson Thanks a lot. 
👍

**Comment by gileadslostson** [comment]
@Marwan2001 thank you! I don't really feel confident enough to dive into a big project and submit changes but sharing some of my code here helps =)

**Comment by Marwan2001** [comment]
Keep up your work.
Hope this repo helps build up your confidence.
P.S - I know less code than you do

**Comment by gileadslostson** [comment]
=) I've been a web dev for about 4 and a half years. Sharing things in the
open is still kind of scary lol

**Pull request merged**
