### PR TITLE
Refactor code and adding virtualenvwrapper

### PR DESCRIPTION
**Pull request by fercreek**
I refactor the first script code with the format syntax of python 3 and adding a fast introduction to Virtual Env Wrapper.

### CODE REVIEW

**Comment by fercreek** [comment]
This commit resolves #7

**Comment by pBouillon** [comment]
@fercreek resolve conflicts and you're good to go

**Comment by fercreek** [comment]
@pBouillon done :+1:

**Comment by pBouillon** [comment]
Merged !

**Pull request merged**
